### ISSUE TITLE
Failing Tests

### ISSUE THREAD

**Issue by yewscion** [dzaima/CBQN#31] opened 2022-08-09 22:32 UTC
Hello,

I've nearly completed packaging cbqn for GNU Guix (with a 5 step bootstrapping process including dbqn and singeli), but a few tests are failing in my build. I've attached the log, starting at the first error, below.

Some possibly relevant information:

- I used clang, per Your recommendation.
- Full bootstrap process is dbqn → cbqn sans tests and singeli with bqn sources compiled with dbqn → cbqn with singeli and full tests.
- I can just skip the failing tests if needed, but they need to be reported here before the package will be accepted.

Are these tests expected to fail, or am I doing something wrong?

```
4
ValueError: Undefined system constant ?file
tests ? ?FLines ?wdpath?file.At path?"/test/cases/prim.bqn"
                       ^^^^^                               
Stack:
1:
#!/gnu/store/5wdp6gknchng4kr2h45ra57divjsn4fx-dbqn-0.2.1/bin/dbqn
?????????????????????????????????????????????????????????????????
tests ? ?FLines ?wdpath?file.At path?"/test/cases/prim.bqn"
                       ^^^^^                               
Exception in thread "main" BQN.errors.ValueError: Undefined system constant ?file
        at BQN.tools.SysVals.getDyn(SysVals.java:132)
        at BQN.Scope.get(Scope.java:134)
        at BQN.Scope.getC(Scope.java:148)
        at BQN.Comp.exec(Comp.java:127)
        at BQN.Comp$SingleComp.exec(Comp.java:678)
        at BQN.Sys.execFile(Sys.java:169)
        at BQN.Main.main(Main.java:115)
AS
AA
166008223392
166008238182
? "Ab" "Ai8" "Ai16" "Ai32" "Af64" "Ah" "Af" "Si8" "Si16" "Si32" "Sf64" "Sh" "Sf" "AbInc" "Ai8Inc" "Ai16Inc" "Ai32Inc" "Af64Inc" "AhInc" "AfInc" "Si8Inc" "Si16Inc" "Si32Inc" "Sf64Inc" "ShInc" "SfInc" ?
? "Ai8" "Ai16" "Ai32" "Af64" "Ah" "Af" "Si8" "Si16" "Si32" "Sf64" "Sh" "Sf" "Ai8Inc" "Ai16Inc" "Ai32Inc" "Af64Inc" "AhInc" "AfInc" "Si8Inc" "Si16Inc" "Si32Inc" "Sf64Inc" "ShInc" "SfInc" ?
? "Ai16" "Ai32" "Af64" "Ah" "Af" "Si16" "Si32" "Sf64" "Sh" "Sf" "Ai16Inc" "Ai32Inc" "Af64Inc" "AhInc" "AfInc" "Si16Inc" "Si32Inc" "Sf64Inc" "ShInc" "SfInc" ?
? "Ai32" "Af64" "Ah" "Af" "Si32" "Sf64" "Sh" "Sf" "Ai32Inc" "Af64Inc" "AhInc" "AfInc" "Si32Inc" "Sf64Inc" "ShInc" "SfInc" ?
? "Af64" "Ah" "Af" "Sf64" "Sh" "Sf" "Af64Inc" "AhInc" "AfInc" "Sf64Inc" "ShInc" "SfInc" ?
? "Ac8" "Ac16" "Ac32" "Ah" "Af" "Sc8" "Sc16" "Sc32" "Sh" "Sf" "Ac8Inc" "Ac16Inc" "Ac32Inc" "AhInc" "AfInc" "Sc8Inc" "Sc16Inc" "Sc32Inc" "ShInc" "SfInc" ?
? "Ac16" "Ac32" "Ah" "Af" "Sc16" "Sc32" "Sh" "Sf" "Ac16Inc" "Ac32Inc" "AhInc" "AfInc" "Sc16Inc" "Sc32Inc" "ShInc" "SfInc" ?
? "Ac32" "Ah" "Af" "Sc32" "Sh" "Sf" "Ac32Inc" "AhInc" "AfInc" "Sc32Inc" "ShInc" "SfInc" ?
? "Ah" "Af" "Sh" "Sf" "AhInc" "AfInc" "ShInc" "SfInc" ?
? "Ah" "Af" "Sh" "Sf" "AhInc" "AfInc" "ShInc" "SfInc" ?
Fraction of matching variation count to ListVariations: 0.9985000000000001 (expected: ~0.999)
166008246641
Fail:
Exp: 0011000111100100010100001101011110010000000111011000010111001001 0111111001011001111011000100001011010010111011001010010110000111 0100001111010101011100010011101010100010111111111111110000100100 1000010010111000111101000101011110111010101000011000000110000000 0000001011010001011100000110001111011010010100110000100001011110 0110111011100010101111110000110101101010000011001110011111001110 01011011101100001111001001100000111000110111001110000
Got: 0011000111100100010100001101011110010000000111011000010101100110 0001100001100101010110011000100011011011101000100111101101010101 0000101100000010001101000111010110101011010110010000100000100100 1000010010111000111101000101011110111010101000011000000110000000 0000001011010001011100000110001111011010010100110000100001011110 0110111011100010101111110000110101101010000011001110011111001110 01011011101100001111001001100000111000110111001110000
Inputs:
r:   0011000111100100010100001101011110010000000111011000010101100110 0001100001100101010110011000100011011011101000100111101101010101 0000101100000010001101000111010110101011010110010000100000100100 1000010010111000111101000101011110111010101000011000000110000000 0000001011010001011100000110001111011010010100110000100001011110 0110111011100010101111110000110101101010000011001110011111001110 01011011101100001111001001100000111000110111001110000
rs:  52
x:   0001001010111100010001100011110111110111010110101000010101111100 0101010111010000010001010011101110111110110011101101011111011011 1101011001011101100101010011101000010100011110000000110100101101 0111100010001110101110010010111111001011001111011000100001011010 0101110110010100101100001110100001111010101011100010011101010100 0101111111111111101011111000110011110001111100110001010110000000 10001101101110001011010001000000110011000111010110011
xs:  207
l:   130
Error: Assertion error
./test/random.bqn:18:
  rByteVals {! "i8arr" ? TY ???}? ?10 # ? is dumb for now, but when it realizes that n?0 is a bitarr this'll need changing
             ^
./test/random.bqn:18:
  rByteVals {! "i8arr" ? TY ???}? ?10 # ? is dumb for now, but when it realizes that n?0 is a bitarr this'll need changing
            ^^^^^^^^^^^^^^^^^^^^^
166008246634
make: Entering directory '/tmp/guix-build-cbqn-0-1.88f6585.drv-0/source/test/ffi'
cc -O3 -g -c -fpic ffiTest.c -o ffiTest.o
cc -shared -olib.so ffiTest.o
Error: Unknown system function ?ffi
make: *** [makefile:15: testLib] Error 1
make: Leaving directory '/tmp/guix-build-cbqn-0-1.88f6585.drv-0/source/test/ffi'
```

**Comment by yewscion** [comment] 2022-08-09 22:36
Also possibly important information:

- I'm basing this on commit 88f65850fa6ac28bc50886c5942652f21d5be924.
- I'm using the "shared-o3" and "o3n-singeli" targets.
- The tests I'm running are: "mainCfgs" "x86Cfgs" "moreCfgs" "cmp" "equal" "copy" "bitcpy" "random" and "ffi".
- I'm assuming the expected 32-bit failed test was the one looking for `stubs-32.h`, otherwise that is also an error.

**Comment by dzaima** [comment] 2022-08-09 23:18
The 32-bit test build in `x86Cfgs.sh` has a single fail due to x87 operations temporarily having more precision, which the tests don't expect; I keep this around as a sanity test that the tester doesn't just spew out "All passed!" unconditionally, but I guess that should be documented somewhere.

**Comment by yewscion** [comment] 2022-08-09 23:18
Is there a reason _not_ to pass `-DTEST_BITCPY` to make? If not, I'll just add it so the test will pass.

And was that addition to dzaima/BQN after the 0.2.1 release tag? If so, could another release be made, so I'm not referencing an arbitrary commit in that package? If possible, Guix prefers packages that reference releases to ones that simply reference commits, because it is easier to know what will work with what.

I'll skip `random.bqn` for now, then, as there is a known failing test that will be fixed in the future. 

Thank You (again) for the quick responses!

**Comment by yewscion** [comment] 2022-08-09 23:22
FWIW I will document that expected fail test in the guix package definition, at least!

**Comment by dzaima** [comment] 2022-08-09 23:24
> Is there a reason _not_ to pass `-DTEST_BITCPY` to make? If not, I'll just add it so the test will pass.

For running tests, it's fine to pass that always. But in the future there might be multiple tests that want their own conflicting flags. `TEST_BITCPY` specifically exposes a `•internal.Temp` that can very violently break approximately everything, by giving direct access to a C function that can copy arbitrary length of arbitrary data in the C heap.

dzaima/BQN releases exist for the one and only purpose of providing Android `apk`s; I suppose I should update it because an old Android release is still not particularly great, but the releases don't mean any sort of real versioning.

**Comment by yewscion** [comment] 2022-08-09 23:31
> TEST_BITCPY specifically exposes a •internal.Temp that can very violently break approximately everything, by giving direct access to a C function that can copy arbitrary length of arbitrary data to arbitrary places in the C heap.

Copy that, definitely leaving that off then.

> dzaima/BQN releases don't mean any sort of real versioning.

Copy that as well, will set the most recent commit as the version, then. I'll reference this thread as the justification; If the version numbers are arbitrary points for inclusion in Android, I doubt they'll overrule commits in priority.

**Comment by dzaima** [comment] 2022-08-09 23:38
Pushed a fixed `test/random.bqn`, and printing a message about the expected fail in `x86Cfgs.sh`.

**Comment by yewscion** [comment] 2022-08-10 02:41
Hmm, so I've updated the build to 9c1cbdc99863b1da0116df61cd832137b196dc5c and unfortunately I've encountered a different failing test, one that seems to crash clang:

```
builtins/inverse.c
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: clang -std=gnu11 -Wall -Wno-unused-function -fms-extensions -DDEBUG -g -DHEAP_VERIFY -Wno-microsoft-anon-tag -Wno-bitwise-instead-of-logical -Wno-unknown-warning-option -DSINGELI=0 -DFFI=2 -MMD -MP -MF obj/def_heapverify/fns.o.d -o obj/def_heapverify/fns.o -c src/builtins/fns.c
1.      <eof> parser at end of file
2.      Code generation
 #0 0x00007ffff03ba2e0 PrintStackTraceSignalHandler(void*) (/gnu/store/579xrf7vz85ynjlk62njaczgnayam1ar-llvm-13.0.1/lib/libLLVMSupport.so.13+0x1ba2e0)
 #1 0x00007ffff03b824c llvm::sys::CleanupOnSignal(unsigned long) (/gnu/store/579xrf7vz85ynjlk62njaczgnayam1ar-llvm-13.0.1/lib/libLLVMSupport.so.13+0x1b824c)
 #2 0x00007ffff02befd8 CrashRecoverySignalHandler(int) (/gnu/store/579xrf7vz85ynjlk62njaczgnayam1ar-llvm-13.0.1/lib/libLLVMSupport.so.13+0xbefd8)
 #3 0x00007ffff4f4cd80 (/gnu/store/5h2w4qi9hk1qzzgi1w83220ydslinr4s-glibc-2.33/lib/libpthread.so.0+0x11d80)
 #4 0x00007fffefe5f203 llvm::DIE::getUnitDie() const (/gnu/store/579xrf7vz85ynjlk62njaczgnayam1ar-llvm-13.0.1/lib/libLLVMAsmPrinter.so.13+0x69203)
 #5 0x00007fffefe81cec llvm::DwarfDebug::finishEntityDefinitions() (/gnu/store/579xrf7vz85ynjlk62njaczgnayam1ar-llvm-13.0.1/lib/libLLVMAsmPrinter.so.13+0x8bcec)
 #6 0x00007fffefe94a92 llvm::DwarfDebug::finalizeModuleInfo() (/gnu/store/579xrf7vz85ynjlk62njaczgnayam1ar-llvm-13.0.1/lib/libLLVMAsmPrinter.so.13+0x9ea92)
 #7 0x00007fffefe99970 llvm::DwarfDebug::endModule() (/gnu/store/579xrf7vz85ynjlk62njaczgnayam1ar-llvm-13.0.1/lib/libLLVMAsmPrinter.so.13+0xa3970)
 #8 0x00007fffefe41d42 llvm::AsmPrinter::doFinalization(llvm::Module&) (/gnu/store/579xrf7vz85ynjlk62njaczgnayam1ar-llvm-13.0.1/lib/libLLVMAsmPrinter.so.13+0x4bd42)
 #9 0x00007ffff1405c9d llvm::FPPassManager::doFinalization(llvm::Module&) (/gnu/store/579xrf7vz85ynjlk62njaczgnayam1ar-llvm-13.0.1/lib/libLLVMCore.so.13+0x205c9d)
#10 0x00007ffff1412238 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/gnu/store/579xrf7vz85ynjlk62njaczgnayam1ar-llvm-13.0.1/lib/libLLVMCore.so.13+0x212238)
#11 0x00007ffff38d7cc2 (anonymous namespace)::EmitAssemblyHelper::EmitAssemblyWithNewPassManager(clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) (.constprop.0) (/gnu/store/zfs41ixykm4z9162gajgs1ndc6bsbcqr-clang-13.0.1/lib/libclangCodeGen.so.13+0xd7cc2)
#12 0x00007ffff38dc1e7 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::StringRef, llvm::Module*, clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) (/gnu/store/zfs41ixykm4z9162gajgs1ndc6bsbcqr-clang-13.0.1/lib/libclangCodeGen.so.13+0xdc1e7)
#13 0x00007ffff3c79a5c clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) (/gnu/store/zfs41ixykm4z9162gajgs1ndc6bsbcqr-clang-13.0.1/lib/libclangCodeGen.so.13+0x479a5c)
#14 0x00007fffee934f19 clang::ParseAST(clang::Sema&, bool, bool) (/gnu/store/zfs41ixykm4z9162gajgs1ndc6bsbcqr-clang-13.0.1/lib/libclangParse.so.13+0x34f19)
#15 0x00007ffff25fc029 clang::FrontendAction::Execute() (/gnu/store/zfs41ixykm4z9162gajgs1ndc6bsbcqr-clang-13.0.1/lib/libclangFrontend.so.13+0xfd029)
#16 0x00007ffff25853cb clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/gnu/store/zfs41ixykm4z9162gajgs1ndc6bsbcqr-clang-13.0.1/lib/libclangFrontend.so.13+0x863cb)
#17 0x00007ffff55022e8 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/gnu/store/zfs41ixykm4z9162gajgs1ndc6bsbcqr-clang-13.0.1/lib/libclangFrontendTool.so.13+0x52e8)
#18 0x00000000004161be cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/gnu/store/zfs41ixykm4z9162gajgs1ndc6bsbcqr-clang-13.0.1/bin/clang-13+0x4161be)
#19 0x00000000004137b6 ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) (/gnu/store/zfs41ixykm4z9162gajgs1ndc6bsbcqr-clang-13.0.1/bin/clang-13+0x4137b6)
#20 0x00007ffff229ee75 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool*) const::'lambda'()>(long) (/gnu/store/zfs41ixykm4z9162gajgs1ndc6bsbcqr-clang-13.0.1/lib/libclangDriver.so.13+0x9ee75)
#21 0x00007ffff02bf0d3 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/gnu/store/579xrf7vz85ynjlk62njaczgnayam1ar-llvm-13.0.1/lib/libLLVMSupport.so.13+0xbf0d3)
#22 0x00007ffff229f1d9 clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool*) const (.part.0) (/gnu/store/zfs41ixykm4z9162gajgs1ndc6bsbcqr-clang-13.0.1/lib/libclangDriver.so.13+0x9f1d9)
#23 0x00007ffff2272c46 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&) const (/gnu/store/zfs41ixykm4z9162gajgs1ndc6bsbcqr-clang-13.0.1/lib/libclangDriver.so.13+0x72c46)
#24 0x00007ffff2273609 clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) const (/gnu/store/zfs41ixykm4z9162gajgs1ndc6bsbcqr-clang-13.0.1/lib/libclangDriver.so.13+0x73609)
#25 0x00007ffff2282739 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) (/gnu/store/zfs41ixykm4z9162gajgs1ndc6bsbcqr-clang-13.0.1/lib/libclangDriver.so.13+0x82739)
#26 0x0000000000411608 main (/gnu/store/zfs41ixykm4z9162gajgs1ndc6bsbcqr-clang-13.0.1/bin/clang-13+0x411608)
#27 0x00007fffeff207dd __libc_start_main (/gnu/store/5h2w4qi9hk1qzzgi1w83220ydslinr4s-glibc-2.33/lib/libc.so.6+0x237dd)
#28 0x000000000041317a _start (/gnu/store/zfs41ixykm4z9162gajgs1ndc6bsbcqr-clang-13.0.1/bin/clang-13+0x41317a)
clang-13: error: clang frontend command failed with exit code 139 (use -v to see invocation)
clang version 13.0.1
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /gnu/store/0wrp34pb4hrd1vvs7hm4aylx11bipyi9-clang-toolchain-13.0.1/bin
clang-13: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-13: note: diagnostic msg: /tmp/guix-build-cbqn-0-1.9c1cbdc.drv-0/fns-55be00.c
clang-13: note: diagnostic msg: /tmp/guix-build-cbqn-0-1.9c1cbdc.drv-0/fns-55be00.sh
clang-13: note: diagnostic msg: 

********************
make[2]: *** [makefile:198: obj/def_heapverify/fns.o] Error 139
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [makefile:164: run_incremental_0] Error 2
make: *** [makefile:21: heapverify] Error 2
clang -std=gnu11 -Wall -Wno-unused-function -fms-extensions  -DDEBUG -DHEAP_VERIFY -DJIT_START=0  -Wno-microsoft-anon-tag -Wno-bitwise-instead-of-logical -Wno-unknown-warning-option -DSINGELI=0 -DFFI=2  -o BQN src/opt/single.c    -no-pie -lm -ldl -Wl,--dynamic-list=include/syms -lffi
alljit+heapverify:
```

**Comment by yewscion** [comment] 2022-08-10 02:50
In case it helps highlight potential issues on my end, here is the complete build log: http://paste.debian.net/1249861/
And here is the check (test) phase only: http://paste.debian.net/1249863/

**Comment by dzaima** [comment] 2022-08-10 04:25
Is that reproducible? I've seen similar things if the source files are modified during compilation, but if it's not that then there aren't many options other than it being a clang bug.

Also - the 32-bit build is not supposed to just outright fail; that suggests you don't have the necessary things installed for cross-compilation to 32-bit x86; which is fine, as long as you don't need to cross-compile, but a test for that still exists regardless because it's useful for me to know that 32-bit builds aren't outright broken.

**Comment by yewscion** [comment] 2022-08-10 15:40
It's reproducible; unfortunately, it occurs every time.

I've included a build done passing the `-v` flag to clang for every invocation:

[jm1xw8pyv96bbgk9c7q1xw0vfq123p-cbqn-0-1.9c1cbdc.drv.gz](https://github.com/dzaima/CBQN/files/9301450/jm1xw8pyv96bbgk9c7q1xw0vfq123p-cbqn-0-1.9c1cbdc.drv.gz)

As for the 32-bit: Yeah, this build is explicitly for x86_64. I have a 32-bit build running now.

**Comment by yewscion** [comment] 2022-08-10 16:14
Looking into the tests further, I noticed that they rebuild BQN multiple times in order to test it. I'm really only concerned with the builds I'm packaging here, though I understand why they are structured that way. So, instead, I'm explicitly running `./BQN -M 1000 "${BQN_Sources}/test/this.bqn"` with the version produced during the build step, now. 

And it passes, so this won't block the packaging for GNU Guix x86_64. I dunno what's causing the above issues, but they _shouldn't_ be relevant to the package, at least.

**Comment by dzaima** [comment] 2022-08-10 18:27
yeah, for testing a specific build, `test/this.bqn` is the thing you want to do.

**Closed** 2022-08-16 11:24 UTC
